name: Build iOS .ipa (no codesign)

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter version / channel (ex: stable or 3.14.0)'
        required: true
        default: 'stable'
  push:
    branches:
      - main

jobs:
  build-ios:
    name: Build iOS 
    runs-on: macos-14

    env:
      APP_PATH: mobile/apps/photos

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set Flutter version
        run: |
          if [ -n "${{ github.event.inputs.flutter_version }}" ]; then
            echo "FLUTTER_VERSION=${{ github.event.inputs.flutter_version }}" >> $GITHUB_ENV
          else
            echo "FLUTTER_VERSION=stable" >> $GITHUB_ENV
          fi

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          architecture: x64

      - name: Show Flutter and Xcode versions
        run: |
          flutter --version
          flutter doctor -v
          xcodebuild -version || true

      - name: Get Flutter dependencies
        working-directory: ${{ env.APP_PATH }}
        run: |
          set -e
          flutter pub get

      - name: Install CocoaPods
        run: |
          set -e
          brew update || true
          brew install cocoapods || sudo gem install cocoapods -N || true
          pod --version || true

      - name: Install iOS pods
        working-directory: ${{ env.APP_PATH }}/ios
        run: |
          set -e
          pod repo update || true
          pod install --verbose || \
          # fallback for pods that need x86_64
          arch -x86_64 pod install --verbose || \
          (echo "::error::pod install failed" && exit 1)

      - name: Build IPA without codesign
        working-directory: ${{ env.APP_PATH }}
        run: |
          set -e
          flutter build ipa --no-codesign --release -v 2>&1 | tee build_ipa.log || (tail -n build_ipa.log && exit 1)

      - name: Debug dump (xcode/podfile/tree)
        working-directory: ${{ env.APP_PATH }}/ios
        run: |
          set -e
          echo "---- xcodebuild -version ----"
          xcodebuild -version || true
          echo "---- Podfile (head) ----"
          head -n 200 Podfile || true
          echo "---- project.pbxproj path ----"
          find . -maxdepth 3 -type f -name project.pbxproj -print || true
          echo "---- ios folder shallow listing ----"
          find . -maxdepth 2 -print

      - name: Verify IPA exists
        run: |
          set -e
          IPA_DIR="${APP_PATH}/build/ios/ipa"
          if ls "${IPA_DIR}"/*.ipa 1> /dev/null 2>&1; then
            echo "IPA found in ${IPA_DIR}:"
            ls -la "${IPA_DIR}"
          else
            echo "::error::No .ipa found in "${IPA_DIR}"
            ls -la "${APP_PATH}/build/ios/" || true
            echo "Last lines of build_ipa.log (if present):"
            [ -f "${APP_PATH}/build_ipa.log" ] && tail -n 200 "${APP_PATH}/build_ipa.log" || true
            exit 1
          fi

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ente-photos-ios-ipa
          path: ${{ env.APP_PATH }}/build/ios/ipa/*.ipa
